// Generated by the protocol buffer compiler.  DO NOT EDIT!


package nie.translator.rtranslator.databases.tatoeba;

public final class LinksData {
    private LinksData() {}

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }
    public interface PairOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Pair)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>uint32 srcSentence = 1;</code>
         * @return The srcSentence.
         */
        int getSrcSentence();

        /**
         * <code>uint32 tgtSentence = 2;</code>
         * @return The tgtSentence.
         */
        int getTgtSentence();
    }
    /**
     * Protobuf type {@code Pair}
     */
    public  static final class Pair extends
            com.google.protobuf.GeneratedMessageLite<
                    Pair, Pair.Builder> implements
            // @@protoc_insertion_point(message_implements:Pair)
            PairOrBuilder {
        private Pair() {
        }
        public static final int SRCSENTENCE_FIELD_NUMBER = 1;
        private int srcSentence_;
        /**
         * <code>uint32 srcSentence = 1;</code>
         * @return The srcSentence.
         */
        @java.lang.Override
        public int getSrcSentence() {
            return srcSentence_;
        }
        /**
         * <code>uint32 srcSentence = 1;</code>
         * @param value The srcSentence to set.
         */
        private void setSrcSentence(int value) {

            srcSentence_ = value;
        }
        /**
         * <code>uint32 srcSentence = 1;</code>
         */
        private void clearSrcSentence() {

            srcSentence_ = 0;
        }

        public static final int TGTSENTENCE_FIELD_NUMBER = 2;
        private int tgtSentence_;
        /**
         * <code>uint32 tgtSentence = 2;</code>
         * @return The tgtSentence.
         */
        @java.lang.Override
        public int getTgtSentence() {
            return tgtSentence_;
        }
        /**
         * <code>uint32 tgtSentence = 2;</code>
         * @param value The tgtSentence to set.
         */
        private void setTgtSentence(int value) {

            tgtSentence_ = value;
        }
        /**
         * <code>uint32 tgtSentence = 2;</code>
         */
        private void clearTgtSentence() {

            tgtSentence_ = 0;
        }

        public static LinksData.Pair parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.Pair parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.Pair parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.Pair parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.Pair parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.Pair parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.Pair parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static LinksData.Pair parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static LinksData.Pair parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static LinksData.Pair parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static LinksData.Pair parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static LinksData.Pair parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }
        public static Builder newBuilder(LinksData.Pair prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * Protobuf type {@code Pair}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        LinksData.Pair, Builder> implements
                // @@protoc_insertion_point(builder_implements:Pair)
                LinksData.PairOrBuilder {
            // Construct using LinksData.Pair.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>uint32 srcSentence = 1;</code>
             * @return The srcSentence.
             */
            @java.lang.Override
            public int getSrcSentence() {
                return instance.getSrcSentence();
            }
            /**
             * <code>uint32 srcSentence = 1;</code>
             * @param value The srcSentence to set.
             * @return This builder for chaining.
             */
            public Builder setSrcSentence(int value) {
                copyOnWrite();
                instance.setSrcSentence(value);
                return this;
            }
            /**
             * <code>uint32 srcSentence = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearSrcSentence() {
                copyOnWrite();
                instance.clearSrcSentence();
                return this;
            }

            /**
             * <code>uint32 tgtSentence = 2;</code>
             * @return The tgtSentence.
             */
            @java.lang.Override
            public int getTgtSentence() {
                return instance.getTgtSentence();
            }
            /**
             * <code>uint32 tgtSentence = 2;</code>
             * @param value The tgtSentence to set.
             * @return This builder for chaining.
             */
            public Builder setTgtSentence(int value) {
                copyOnWrite();
                instance.setTgtSentence(value);
                return this;
            }
            /**
             * <code>uint32 tgtSentence = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearTgtSentence() {
                copyOnWrite();
                instance.clearTgtSentence();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Pair)
        }
        @java.lang.Override
        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new LinksData.Pair();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    java.lang.Object[] objects = new java.lang.Object[] {
                            "srcSentence_",
                            "tgtSentence_",
                    };
                    java.lang.String info =
                            "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
                                    "";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<LinksData.Pair> parser = PARSER;
                    if (parser == null) {
                        synchronized (LinksData.Pair.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<LinksData.Pair>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:Pair)
        private static final LinksData.Pair DEFAULT_INSTANCE;
        static {
            Pair defaultInstance = new Pair();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    Pair.class, defaultInstance);
        }

        public static LinksData.Pair getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<Pair> PARSER;

        public static com.google.protobuf.Parser<Pair> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface PairListOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PairList)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>repeated .Pair items = 1;</code>
         */
        java.util.List<LinksData.Pair>
        getItemsList();
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        LinksData.Pair getItems(int index);
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        int getItemsCount();
    }
    /**
     * Protobuf type {@code PairList}
     */
    public  static final class PairList extends
            com.google.protobuf.GeneratedMessageLite<
                    PairList, PairList.Builder> implements
            // @@protoc_insertion_point(message_implements:PairList)
            PairListOrBuilder {
        private PairList() {
            items_ = emptyProtobufList();
        }
        public static final int ITEMS_FIELD_NUMBER = 1;
        private com.google.protobuf.Internal.ProtobufList<LinksData.Pair> items_;
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        @java.lang.Override
        public java.util.List<LinksData.Pair> getItemsList() {
            return items_;
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        public java.util.List<? extends LinksData.PairOrBuilder>
        getItemsOrBuilderList() {
            return items_;
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        @java.lang.Override
        public int getItemsCount() {
            return items_.size();
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        @java.lang.Override
        public LinksData.Pair getItems(int index) {
            return items_.get(index);
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        public LinksData.PairOrBuilder getItemsOrBuilder(
                int index) {
            return items_.get(index);
        }
        private void ensureItemsIsMutable() {
            com.google.protobuf.Internal.ProtobufList<LinksData.Pair> tmp = items_;
            if (!tmp.isModifiable()) {
                items_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
            }
        }

        /**
         * <code>repeated .Pair items = 1;</code>
         */
        private void setItems(
                int index, LinksData.Pair value) {
            value.getClass();
            ensureItemsIsMutable();
            items_.set(index, value);
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        private void addItems(LinksData.Pair value) {
            value.getClass();
            ensureItemsIsMutable();
            items_.add(value);
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        private void addItems(
                int index, LinksData.Pair value) {
            value.getClass();
            ensureItemsIsMutable();
            items_.add(index, value);
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        private void addAllItems(
                java.lang.Iterable<? extends LinksData.Pair> values) {
            ensureItemsIsMutable();
            com.google.protobuf.AbstractMessageLite.addAll(
                    values, items_);
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        private void clearItems() {
            items_ = emptyProtobufList();
        }
        /**
         * <code>repeated .Pair items = 1;</code>
         */
        private void removeItems(int index) {
            ensureItemsIsMutable();
            items_.remove(index);
        }

        public static LinksData.PairList parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.PairList parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.PairList parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.PairList parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.PairList parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.PairList parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.PairList parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static LinksData.PairList parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static LinksData.PairList parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static LinksData.PairList parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static LinksData.PairList parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static LinksData.PairList parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }
        public static Builder newBuilder(LinksData.PairList prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * Protobuf type {@code PairList}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        LinksData.PairList, Builder> implements
                // @@protoc_insertion_point(builder_implements:PairList)
                LinksData.PairListOrBuilder {
            // Construct using LinksData.PairList.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            /**
             * <code>repeated .Pair items = 1;</code>
             */
            @java.lang.Override
            public java.util.List<LinksData.Pair> getItemsList() {
                return java.util.Collections.unmodifiableList(
                        instance.getItemsList());
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            @java.lang.Override
            public int getItemsCount() {
                return instance.getItemsCount();
            }/**
             * <code>repeated .Pair items = 1;</code>
             */
            @java.lang.Override
            public LinksData.Pair getItems(int index) {
                return instance.getItems(index);
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder setItems(
                    int index, LinksData.Pair value) {
                copyOnWrite();
                instance.setItems(index, value);
                return this;
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder setItems(
                    int index, LinksData.Pair.Builder builderForValue) {
                copyOnWrite();
                instance.setItems(index,
                        builderForValue.build());
                return this;
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder addItems(LinksData.Pair value) {
                copyOnWrite();
                instance.addItems(value);
                return this;
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder addItems(
                    int index, LinksData.Pair value) {
                copyOnWrite();
                instance.addItems(index, value);
                return this;
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder addItems(
                    LinksData.Pair.Builder builderForValue) {
                copyOnWrite();
                instance.addItems(builderForValue.build());
                return this;
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder addItems(
                    int index, LinksData.Pair.Builder builderForValue) {
                copyOnWrite();
                instance.addItems(index,
                        builderForValue.build());
                return this;
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder addAllItems(
                    java.lang.Iterable<? extends LinksData.Pair> values) {
                copyOnWrite();
                instance.addAllItems(values);
                return this;
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder clearItems() {
                copyOnWrite();
                instance.clearItems();
                return this;
            }
            /**
             * <code>repeated .Pair items = 1;</code>
             */
            public Builder removeItems(int index) {
                copyOnWrite();
                instance.removeItems(index);
                return this;
            }

            // @@protoc_insertion_point(builder_scope:PairList)
        }
        @java.lang.Override
        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new LinksData.PairList();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    java.lang.Object[] objects = new java.lang.Object[] {
                            "items_",
                            LinksData.Pair.class,
                    };
                    java.lang.String info =
                            "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<LinksData.PairList> parser = PARSER;
                    if (parser == null) {
                        synchronized (LinksData.PairList.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<LinksData.PairList>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:PairList)
        private static final LinksData.PairList DEFAULT_INSTANCE;
        static {
            PairList defaultInstance = new PairList();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    PairList.class, defaultInstance);
        }

        public static LinksData.PairList getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<PairList> PARSER;

        public static com.google.protobuf.Parser<PairList> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }

    public interface DataMapOrBuilder extends
            // @@protoc_insertion_point(interface_extends:DataMap)
            com.google.protobuf.MessageLiteOrBuilder {

        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */
        int getDataCount();
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */
        boolean containsData(
                java.lang.String key);
        /**
         * Use {@link #getDataMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, LinksData.PairList>
        getData();
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */
        java.util.Map<java.lang.String, LinksData.PairList>
        getDataMap();
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */

        /* nullable */
        LinksData.PairList getDataOrDefault(
                java.lang.String key,
                /* nullable */
                LinksData.PairList defaultValue);
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */

        LinksData.PairList getDataOrThrow(
                java.lang.String key);
    }
    /**
     * Protobuf type {@code DataMap}
     */
    public  static final class DataMap extends
            com.google.protobuf.GeneratedMessageLite<
                    DataMap, DataMap.Builder> implements
            // @@protoc_insertion_point(message_implements:DataMap)
            DataMapOrBuilder {
        private DataMap() {
        }
        public static final int DATA_FIELD_NUMBER = 1;
        private static final class DataDefaultEntryHolder {
            static final com.google.protobuf.MapEntryLite<
                    java.lang.String, LinksData.PairList> defaultEntry =
                    com.google.protobuf.MapEntryLite
                            .<java.lang.String, LinksData.PairList>newDefaultInstance(
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                    LinksData.PairList.getDefaultInstance());
        }
        private com.google.protobuf.MapFieldLite<
                java.lang.String, LinksData.PairList> data_ =
                com.google.protobuf.MapFieldLite.emptyMapField();
        private com.google.protobuf.MapFieldLite<java.lang.String, LinksData.PairList>
        internalGetData() {
            return data_;
        }
        private com.google.protobuf.MapFieldLite<java.lang.String, LinksData.PairList>
        internalGetMutableData() {
            if (!data_.isMutable()) {
                data_ = data_.mutableCopy();
            }
            return data_;
        }
        @java.lang.Override

        public int getDataCount() {
            return internalGetData().size();
        }
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */
        @java.lang.Override

        public boolean containsData(
                java.lang.String key) {
            java.lang.Class<?> keyClass = key.getClass();
            return internalGetData().containsKey(key);
        }
        /**
         * Use {@link #getDataMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, LinksData.PairList> getData() {
            return getDataMap();
        }
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String, LinksData.PairList> getDataMap() {
            return java.util.Collections.unmodifiableMap(
                    internalGetData());
        }
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */
        @java.lang.Override

        public LinksData.PairList getDataOrDefault(
                java.lang.String key,
                LinksData.PairList defaultValue) {
            java.lang.Class<?> keyClass = key.getClass();
            java.util.Map<java.lang.String, LinksData.PairList> map =
                    internalGetData();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */
        @java.lang.Override

        public LinksData.PairList getDataOrThrow(
                java.lang.String key) {
            java.lang.Class<?> keyClass = key.getClass();
            java.util.Map<java.lang.String, LinksData.PairList> map =
                    internalGetData();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }
        /**
         * <code>map&lt;string, .PairList&gt; data = 1;</code>
         */
        private java.util.Map<java.lang.String, LinksData.PairList>
        getMutableDataMap() {
            return internalGetMutableData();
        }

        public static LinksData.DataMap parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.DataMap parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.DataMap parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.DataMap parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.DataMap parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data);
        }
        public static LinksData.DataMap parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, data, extensionRegistry);
        }
        public static LinksData.DataMap parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static LinksData.DataMap parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static LinksData.DataMap parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input);
        }
        public static LinksData.DataMap parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
        }
        public static LinksData.DataMap parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input);
        }
        public static LinksData.DataMap parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageLite.parseFrom(
                    DEFAULT_INSTANCE, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return (Builder) DEFAULT_INSTANCE.createBuilder();
        }
        public static Builder newBuilder(LinksData.DataMap prototype) {
            return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
        }

        /**
         * Protobuf type {@code DataMap}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        LinksData.DataMap, Builder> implements
                // @@protoc_insertion_point(builder_implements:DataMap)
                LinksData.DataMapOrBuilder {
            // Construct using LinksData.DataMap.newBuilder()
            private Builder() {
                super(DEFAULT_INSTANCE);
            }


            @java.lang.Override

            public int getDataCount() {
                return instance.getDataMap().size();
            }
            /**
             * <code>map&lt;string, .PairList&gt; data = 1;</code>
             */
            @java.lang.Override

            public boolean containsData(
                    java.lang.String key) {
                java.lang.Class<?> keyClass = key.getClass();
                return instance.getDataMap().containsKey(key);
            }

            public Builder clearData() {
                copyOnWrite();
                instance.getMutableDataMap().clear();
                return this;
            }
            /**
             * <code>map&lt;string, .PairList&gt; data = 1;</code>
             */

            public Builder removeData(
                    java.lang.String key) {
                java.lang.Class<?> keyClass = key.getClass();
                copyOnWrite();
                instance.getMutableDataMap().remove(key);
                return this;
            }
            /**
             * Use {@link #getDataMap()} instead.
             */
            @java.lang.Override
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, LinksData.PairList> getData() {
                return getDataMap();
            }
            /**
             * <code>map&lt;string, .PairList&gt; data = 1;</code>
             */
            @java.lang.Override
            public java.util.Map<java.lang.String, LinksData.PairList> getDataMap() {
                return java.util.Collections.unmodifiableMap(
                        instance.getDataMap());
            }
            /**
             * <code>map&lt;string, .PairList&gt; data = 1;</code>
             */
            @java.lang.Override

            public LinksData.PairList getDataOrDefault(
                    java.lang.String key,
                    LinksData.PairList defaultValue) {
                java.lang.Class<?> keyClass = key.getClass();
                java.util.Map<java.lang.String, LinksData.PairList> map =
                        instance.getDataMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }
            /**
             * <code>map&lt;string, .PairList&gt; data = 1;</code>
             */
            @java.lang.Override

            public LinksData.PairList getDataOrThrow(
                    java.lang.String key) {
                java.lang.Class<?> keyClass = key.getClass();
                java.util.Map<java.lang.String, LinksData.PairList> map =
                        instance.getDataMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }
            /**
             * <code>map&lt;string, .PairList&gt; data = 1;</code>
             */
            public Builder putData(
                    java.lang.String key,
                    LinksData.PairList value) {
                java.lang.Class<?> keyClass = key.getClass();
                java.lang.Class<?> valueClass = value.getClass();
                copyOnWrite();
                instance.getMutableDataMap().put(key, value);
                return this;
            }
            /**
             * <code>map&lt;string, .PairList&gt; data = 1;</code>
             */
            public Builder putAllData(
                    java.util.Map<java.lang.String, LinksData.PairList> values) {
                copyOnWrite();
                instance.getMutableDataMap().putAll(values);
                return this;
            }

            // @@protoc_insertion_point(builder_scope:DataMap)
        }
        @java.lang.Override
        @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
        protected final java.lang.Object dynamicMethod(
                com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
                java.lang.Object arg0, java.lang.Object arg1) {
            switch (method) {
                case NEW_MUTABLE_INSTANCE: {
                    return new LinksData.DataMap();
                }
                case NEW_BUILDER: {
                    return new Builder();
                }
                case BUILD_MESSAGE_INFO: {
                    java.lang.Object[] objects = new java.lang.Object[] {
                            "data_",
                            DataDefaultEntryHolder.defaultEntry,
                    };
                    java.lang.String info =
                            "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u00012";
                    return newMessageInfo(DEFAULT_INSTANCE, info, objects);
                }
                // fall through
                case GET_DEFAULT_INSTANCE: {
                    return DEFAULT_INSTANCE;
                }
                case GET_PARSER: {
                    com.google.protobuf.Parser<LinksData.DataMap> parser = PARSER;
                    if (parser == null) {
                        synchronized (LinksData.DataMap.class) {
                            parser = PARSER;
                            if (parser == null) {
                                parser =
                                        new DefaultInstanceBasedParser<LinksData.DataMap>(
                                                DEFAULT_INSTANCE);
                                PARSER = parser;
                            }
                        }
                    }
                    return parser;
                }
                case GET_MEMOIZED_IS_INITIALIZED: {
                    return (byte) 1;
                }
                case SET_MEMOIZED_IS_INITIALIZED: {
                    return null;
                }
            }
            throw new UnsupportedOperationException();
        }


        // @@protoc_insertion_point(class_scope:DataMap)
        private static final LinksData.DataMap DEFAULT_INSTANCE;
        static {
            DataMap defaultInstance = new DataMap();
            // New instances are implicitly immutable so no need to make
            // immutable.
            DEFAULT_INSTANCE = defaultInstance;
            com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                    DataMap.class, defaultInstance);
        }

        public static LinksData.DataMap getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static volatile com.google.protobuf.Parser<DataMap> PARSER;

        public static com.google.protobuf.Parser<DataMap> parser() {
            return DEFAULT_INSTANCE.getParserForType();
        }
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
